# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- checkout: self
  fetchDepth: 0

    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'C:\Users\guili\source\repos\TalentZ\TestTalentZ'
  displayName: 'Run a one-line script'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: 'C:\Users\guili\source\repos\TalentZ\TestTalentZ'
    pathToSources: 'C:\Users\guili\agent-backend\_work\1\TestResults'
    failIfCoverageEmpty: false