name: talentz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter_card_swiper:
    git:
      url: https://github.com/LemonsSquirrel/flutter_card_swiper.git
  flutter:
    sdk: flutter
  flutter_dotenv: 5.1.0
  dio: 5.4.3+1
  flutter_carousel_widget: ^2.2.0
  logger: ^2.5.0
  cupertino_icons: ^1.0.6
  fluttericon: ^2.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.17
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
    - family: Montserrat-Italic
      fonts:
        - asset: lib/assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
    - family: CustomIcons
      fonts:
        - asset: lib/assets/fonts/CustomIcons.ttf
  
  uses-material-design: true

  assets:
    - .env
    - lib/assets/images/
    - lib/assets/images/svgs/
