name: talentz_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter_card_swiper:
    git:
      url: https://github.com/LemonsSquirrel/flutter_card_swiper.git
  flutter:
    sdk: flutter
  flutter_dotenv: 5.1.0
  dio: 5.4.3+1
  flutter_carousel_widget: ^2.2.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - lib/assets/images/
