on:
  push:
    branches:
      - main

name: Test, Build and Release apk
jobs:

  pull:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses : actions/checkout@v2
    
    - name: Pull repository to server
      run: |
        git pull origin main
  
  build:
    name: Build apk
    runs-on: ubuntu-latest
    needs: pull
    defaults:
      run:
        working-directory: talentz_mobile
    steps:
    - name: Chechout repository
      uses: actions/checkout@v2
    - name: Java setup
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Set up flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.19.6'
    - name: Install dependencies
      run: flutter pub get
    - name: Build Flutter project
      run: flutter build apk --debug --split-per-abi
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: talentz_mobile/build/app/outputs/flutter-apk/
  
  retrieve:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout repository
      uses : actions/checkout@v2
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: TalentZ/talentz_mobile/build/app/outputs/flutter-apk
  
  copy:
    runs-on: self-hosted
    needs: retrieve

    steps:
    - name: Checkout repository
      uses : actions/checkout@v2
    
    - name: Copy files to distant server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        SERVER_USER="root"
        SERVER_IP="31.207.38.42"
        SERVER_PATH="/root/TalentZ"

        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known-hosts

        ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "rm -rf $SERVER_PATH"

        rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ $SERVER_USER@$SERVER_IP:$SERVER_PATH
    - name: Run Docker Compose on maind distant server
      run: |
        ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP << EOF
          cd /root/TalentZ
          docker compose down
          docker compose up --build
        EOF